name       : patchutils
version    : 0.3.4
release    : 2
source     :
    - https://github.com/twaugh/patchutils/archive/0.3.4.tar.gz : 49510da6a9627bfe3c340eed69040ca513cdc56d0bc82dacec07c13e766ba550
license    : GPL-2.0-or-later
component  : programming.tools
summary    : Collection of patch utilities
description: |
    Collection of patch utilities
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
